name: molecule-viewer
channels:
  - anaconda
  - schrodinger 
  - rdkit
dependencies:
  - python=3.7
  - pip
  - pymol-bundle=2.4.1
  - rdkit=2020.09.1.0
  - pip:
    - chembl_webresource_client==0.10.2